site_name: Scraping Experiments
theme: 
  name: material
markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - stylesheets/extra.css
nav:
  - introduction.md
  - philosophy.md
  - Making Requests:
    - requests/libraries.md
    - requests/caching.md
  - Parsing HTML:
    - parsing/intro.md
    - parsing/features.md
    - parsing/performance.md
    - parsing/bad_html.md
  # object validation?
  # ORM/etc.
  # git scraping
  # running scrapers
  - License: license.md
  - About: license.md
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.