project:
  type: book

book:
  title: "Art of Web Scraping"
  author: "James Turk"
  # favicon: TODO.png
  sidebar: 
    #logo: TODO.png
    style: docked
    search: true
  repo-url: https://github.com/jamesturk/aows/
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  downloads: [pdf]
  #image: "TODO.png"

  chapters:
    - index.qmd
    - part: "Understanding Web Scraping"
      chapters: 
        - 101.qmd
        - philosophy.md
        - best-practices.qmd
        - ethical-legal.qmd
    - part: "Python Scraping Ecosystem"
      chapters:
        - requests/index.qmd
        - parsing/index.qmd
        - other-libraries.qmd
  appendices: 
      - selectors.qmd
  

format:
  html:
    theme:
      light: flatly
      dark: darkly
      # pulse, sandstone, solar
    code-fold: false
    number-depth: 3

  pdf:
    toc: true
    number-sections: true